### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by TakeshiBito** [nciske/salesforce-wordpress-to-lead#101]
Thank you for your help.

When importing, I get a PHP error on PHP 7.3.16 and PHP 7.4.4.4 in my environment.
It works with PHP 7.2.29.

The errors are numerous and include the following

Warning: preg_match(): Compilation failed: invalid range in character class at offset 4 in /home/*****/****************/public_html/wp-content/ plugins/salesforce-wordpress-to-lead/lib/simple_html_dom.php on line 1364

I hope you can resolve this.
Thank you for your help.

Translated with www.DeepL.com/Translator (free version)
